"""add citation format table

Revision ID: 0d0e7d20ee58
Revises: c8288ded28fc
Create Date: 2026-01-11 03:34:18.832935

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '0d0e7d20ee58'
down_revision = 'c8288ded28fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    citation_format = op.create_table(
        'citation_format',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('code', sa.String(length=64), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('template', sa.Text(), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.text('0')),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', name='uq_citation_format_code')
    )
    op.create_index('ix_citation_format_user_id', 'citation_format', ['user_id'], unique=False)

    system_formats = [
        {
            'code': 'system_gbt',
            'name': 'GB/T 7714',
            'description': '中文期刊常用标准',
            'template': '作者. 标题[J]. 期刊, 年, 卷(期): 页码.'
        },
        {
            'code': 'system_apa',
            'name': 'APA',
            'description': 'American Psychological Association',
            'template': 'Author, A. A. (Year). Title. Journal, Volume(Issue), pages.'
        },
        {
            'code': 'system_mla',
            'name': 'MLA',
            'description': 'Modern Language Association',
            'template': 'Author. \"Title.\" Journal Volume.Issue (Year): pages.'
        },
    ]
    now = datetime.utcnow()
    op.bulk_insert(
        citation_format,
        [
            {
                'code': item['code'],
                'name': item['name'],
                'description': item['description'],
                'template': item['template'],
                'is_system': True,
                'created_at': now,
                'updated_at': now,
                'user_id': None,
            }
            for item in system_formats
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citation_format_user_id', table_name='citation_format')
    op.drop_table('citation_format')
    # ### end Alembic commands ###
