"""add remark field for document notes

Revision ID: 56844475f12b
Revises: a360f19a5b5d
Create Date: 2026-03-25 17:47:11.593059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56844475f12b'
down_revision = 'a360f19a5b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesis_degree', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('thesis_degree')

    # ### end Alembic commands ###
