"""add remark field for document notes

Revision ID: a360f19a5b5d
Revises: bc7b2edbe3cd
Create Date: 2026-03-11 00:36:38.038266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a360f19a5b5d'
down_revision = 'bc7b2edbe3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citation_format', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citation_format_user_id'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True, comment='备注/笔记'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('remark')

    with op.batch_alter_table('citation_format', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_format_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
